### ISSUE TITLE
How to exclude columns?

### ISSUE THREAD

**Issue by dseptem** [OmbraDiFenice/table2csv#4]
I tried using a Jquery selector like "th:contains('blah')" (blah being the value of the header) and it indeed filters the column, but screws up the rest of the CSV because the columns and their values are misaligned.

Should all cells in the column to be excluded have a class or something like that?

**Comment by dseptem** [comment]
Ok, I answered my own questions. All ths and tds to be excluded should have the same class.
It's not enough to select the header.

**Comment by sheevam76** [comment]
Hello, it was better if you had told the exact solution.
The solution is 
excludeColumns : '.class-name'
and this class name should be in "th" as well as in all the "td" columns.
